version: "3"
services:
  web:
    container_name: web
    build:
      context: ./apps/web
      dockerfile: .dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - rxt_network
    depends_on:
      cms:
        condition: service_started

    env_file:
      - ./apps/web/.env
      - ./apps/web/.env.prod
  cms:
    container_name: cms
    build:
      context: ./apps/api
      dockerfile: .dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - rxt_network
    env_file:
      - ./apps/api/.env

networks:
  rxt_network:
    external: true
volumes:
  data:
    driver: local
